name: update stars
on:
  workflow_dispatch:
  schedule:
  - cron: "0 1 * * *"
  
jobs:
  update-stars:
    name: update stars
    runs-on: ubuntu-latest
    steps:
    
    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: America/Sao_Paulo
    
    - name: Check out code 
      uses: actions/checkout@v1
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install starred
        
    - name: update repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: starred --username waldirborbajr --repository github-bookmarks-stars --sort --token ${GITHUB_TOKEN} --message 'Auto updated via github action'
